# Generated by Django 5.2.8 on 2026-05-13 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('FLOOD', 'Flood Relief'), ('TYPHOON', 'Typhoon Aid'), ('FIRE', 'Fire Victim Support'), ('EARTHQUAKE', 'Earthquake Response'), ('MEDICAL', 'Medical Outreach'), ('OTHER', 'Other Emergency')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_personnel', models.ManyToManyField(related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
