# Generated by Django 5.2.8 on 2026-05-13 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('priority_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('barangay', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('household_number', models.CharField(max_length=50)),
                ('family_member_count', models.IntegerField(default=1)),
                ('children_count', models.IntegerField(default=0)),
                ('elderly_count', models.IntegerField(default=0)),
                ('pwd_count', models.IntegerField(default=0)),
                ('employment_status', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_condition', models.CharField(max_length=100)),
                ('priority_score', models.IntegerField(default=0)),
                ('priority_level', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority')], default='LOW', max_length=10)),
                ('claim_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('PARTIAL', 'Partially Claimed')], default='PENDING', max_length=10)),
                ('valid_id_photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/ids/')),
                ('beneficiary_photo', models.ImageField(blank=True, null=True, upload_to='beneficiaries/photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='beneficiaries/qr/')),
                ('claim_reference_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='beneficiaries.category')),
            ],
        ),
    ]
