# Generated by Django 5.2.8 on 2026-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='claim_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('PARTIAL', 'Partially Claimed')], default='PENDING', max_length=20),
        ),
    ]
