# Generated by Django 5.2.8 on 2026-05-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='dafac_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='DAFAC Card #'),
        ),
    ]
