# Generated by Django 5.2.8 on 2026-05-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_beneficiary_dafac_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relationship_to_head', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other Relative')], max_length=20)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('is_pwd', models.BooleanField(default=False, verbose_name='PWD')),
                ('is_senior_citizen', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_lactating_mother', models.BooleanField(default=False)),
                ('is_solo_parent', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='beneficiaries.beneficiary')),
            ],
        ),
    ]
