# Generated by Django 5.2.8 on 2026-05-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_familymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='verification_status',
        ),
    ]
